### ISSUE TITLE
PSFSIG outside valid range

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#427] opened 2021-03-22 16:57 UTC
I was running an LSST simulation and, for a particular choice of cadence, I hit this bug:
```
  - FATAL ERROR ABORT called by interp_GALMAG_HOSTLIB 
  - g-PSFSIG=2.424000 asec outside valid range ( 0.01 -  2.13) 
  - Cannot extrapolate GALMAG. SIMLIB_ID=19721 

```
Is it possible to extend the PSFSIG range to 0.01 - 3 asec?
Thanks,
Maria

**Comment by maria-vincenzi** [comment] 2021-03-22 16:59
If necessary, the SIMLIB I'm using is on cori (NERSC) in `/global/cscratch1/sd/mvincenz/simlibs/rolling_scale1.0_nslice2_v1.7_10yrs_WFD.simlib.COADD`

**Comment by RickKessler** [comment] 2021-03-23 02:32
please post command to reproduce error. The ABORT above looks like a UNITS problem.

**Comment by maria-vincenzi** [comment] 2021-03-23 08:08
I created the folder:
`/global/homes/m/mvincenz/snana_debug/PSFSIG
`on cori.

If you run the command in `test_PSFSIG` you should be able to reproduce the error.
Thanks!

**Comment by RickKessler** [comment] 2021-03-23 23:06
this LSST SIMLIB has an epoch where PSF(FWHM) is just slightly above 5'' ... which exceeds the boundary of the PSF-binned map used in interp_GALMAG. To avoid aborts when PSF is outside the map range, I fixed interp_GALMAG to use the PSF value at the map edge (instead of abort). Hopefully such extreme epochs get tossed in the analysis.

**Closed by RickKessler** 2021-03-23 23:06 UTC
