### ISSUE TITLE
check crazy flux with SALT3-NIR

### ISSUE THREAD

**Issue by pmacias** [RickKessler/SNANA#1094] opened 2023-03-08 22:35 UTC
Hi Rick,

I'm getting the check crazy flux error while using SALT3-NIR for Roman runs with Pippin. Config file is here

/project2/rkessler/SURVEYS/WFIRST/USERS/pmacias/dev/pippin/ROMAN_ALL_20DAY.ymlv

Here are the dump details:

tail /scratch/midway2/rkessler/PIPPIN_OUTPUT/ROMAN_ALL_20DAY/1_SIM/WFIRST_SIMDATA_G10/LOGS/TMP_pmac_PIP_ROMAN_ALL_20DAY_WFIRST_SIMDATA_G10_SNIaMODEL0-0004_57277.LOG

# ================================================ 
  PRE-ABORT DUMP from function check_crazyFlux : 

 xxx ------------------------------------------------------- 
 xxx dumpEpoch_fluxNoise_apply called from check_crazyFlux 
 xxx CID=33184  MJD=55020.013  ifilt_obs=40(F)  LIBID=94
 xxx z=0.096  mu=38.218  Trest=-10.60  Tobs=-11.63  genmag(F)=  12.3  
 xxx GEN(AV,RV) =  -9.000 ,  -9.000  SHAPEPAR=  0.872  (c=  0.025,mB=18.808)
 xxx 

I saw from previous closed issues that it might be a model normalization, but I currently have c values restricted from 

GENRANGE_SALT2c:   -0.300  0.500  

and this error was not happening when I ran this in 2022. Any tips?

**Comment by pmacias** [comment] 2023-03-28 18:48
Hi Rick,

I am still getting the same error when running with the public version of SALT3NIR. It's called from this input file

/project2/rkessler/SURVEYS/WFIRST/USERS/pmacias/dev/sim/SIMGEN_SALT3NIR_MODEL.input

Output is here:

tail /scratch/midway2/rkessler/PIPPIN_OUTPUT/ROMAN_ALL_20DAY/1_SIM/WFIRST_SIMDATA_G10/LOGS/TMP_pmac_PIP_ROMAN_ALL_20DAY_WFIRST_SIMDATA_G10_SNIaMODEL0-0004_40320.LOG

 xxx dumpEpoch_fluxNoise_apply called from check_crazyFlux 
 xxx CID=85805  MJD=55705.013  ifilt_obs=40(F)  LIBID=119
 xxx z=0.101  mu=38.332  Trest= -2.60  Tobs=-2.86  genmag(F)=  13.2  
 xxx GEN(AV,RV) =  -9.000 ,  -9.000  SHAPEPAR=  0.891  (c=  0.024,mB=18.917)

Thanks!

**Comment by RickKessler** [comment] 2023-03-30 02:42
To reproduce this abort quickly, set
 GENRANGE_REDSHIFT: 0.02 0.2

The problem is that the reddest wave bins have crazy large intrinsic-scatter smear, so I set a more sensible abort trap as shown in the attached figure. There are two ways to fix this: 
1. manually hack SALT3.P22-NIR/salt3_color_dispersion.dat.gz and force dispersions values to be less-or-equal to ~1 mag (note that it goes up to 5 mag at 18,000A)
2. restrict high-wave end for "RESTLAMBDA_RANGE: 2800 17000" in SALT3.INFO.
3. fix training code to avoid crazy color dispersion values.

<img width="827" alt="crazy_magSmear" src="https://user-images.githubusercontent.com/24592476/228713790-759a45e7-19d5-4e98-a85f-5c1cf37fe2eb.png">

**Comment by RickKessler** [comment] 2023-04-03 02:00
in SALT3.INFO file I added
   COLOR_DISP_MAX: 2

**Comment by RickKessler** [comment] 2023-04-21 21:21
gonna close this issue, but please re-open if problem persists.

**Closed by RickKessler** 2023-04-21 21:21 UTC
