### ISSUE TITLE
SNDATA_ROOT sample input files contain invalid wfit args

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#1339] opened 2024-05-01 05:20 UTC
`$SNDATA_ROOT/sample_input_files/DES-SN5YR/base_files/bbc/BBC_des5yr.input` contains:

`WFITMUDIF_OPT: -speed_flag_chi2 0 -wsteps 801 -ommin 0.0 -ommax 1 -omsteps 501 -hmin 40 -hmax 100 -hsteps 501 -ompri 0.315 -dompri 10`

But the `-hmin` and `-hmax` args aren't recognised by wfit

**Comment by RickKessler** [comment] 2024-05-01 16:26
I forgot to announce that the obsolete h-parameters (for Hubble constant) are no longer valid because they have never been used and are misleading: 
need to remove     -hmin 40 -hmax 100 -hsteps 501

**Comment by RickKessler** [comment] 2024-05-03 01:53
Just noticed that the problem is in publicly released input file ... so I fixed it.

**Closed by RickKessler** 2024-05-03 01:53 UTC
