### ISSUE TITLE
Error while compiling SNANA

### ISSUE THREAD

**Issue by bcarreres** [RickKessler/SNANA#175] opened 2020-07-08 08:14 UTC
Hi, I've got an issue during the compilation of SNANA can you help me?
I have this error message : 

../util/set_Cpreproc_flags.py``
 LIST_CFLAG = ['USE_HBOOK', 'USE_ROOT', 'USE_PYTHON']
Number of C preproc flags: 3
# --------------------------------------------- 
Check C preproc flag: USE_HBOOK
 File: ../src/sntools_output.h
 ENV(CERN_DIR) = None 
 SET_CFLAG = False
	USE_HBOOK not set -> return
# --------------------------------------------- 
 Check C preproc flag: USE_ROOT
 File: ../src/sntools_output.h
 ENV(ROOT_DIR) = None 
 SET_CFLAG = False
	 USE_ROOT not set -> return
# --------------------------------------------- 
 Check C preproc flag: USE_PYTHON
 File: ../src/genmag_BYOSED.h
 ENV(SNANA_PYTHON_DIR) = None 
 SET_CFLAG = False
	 USE_PYTHON not set -> return

 Done.
mkdir -p ../obj
mkdir -p ../bin
mkdir -p ../lib	
(cd ../obj;  gfortran  -c -static -m64 -O1    ../src/fcasplit.F ) 
gfortran -o  ../bin/fcasplit -m64 -lpthread  \
../obj/fcasplit.o 
(cd ../obj;  rm fcasplit.o ) 
(cd ../obj; \
cc -c -static -m64 -O1     -I//renoir/carreres/CosmoSoft/cfitsio_directory/include ../src/sntools_output.c )
../src/sntools_output.c: In function ‘TABLEFILE_OPEN’:
../src/sntools_output.c:432:5: error: ‘FMT’ undeclared (first use in this function)
     FMT = STRING_TABLEFILE_TYPE[TYPE_FLAG]; // "HBOOK"
     ^~~
../src/sntools_output.c:432:5: note: each undeclared identifier is reported only once for each function it appears in
../src/sntools_output.c:433:13: error: ‘ENV’ undeclared (first use in this function)
     sprintf(ENV,"CERN_DIR");                // required ENV for make
             ^~~
Makefile:896: recipe for target '../obj/sntools_output.o' failed
make: *** [../obj/sntools_output.o] Error 1

I do not use HBOOK or ROOT for the compilation

**Comment by bcarreres** [comment] 2020-07-08 10:20
UPDATE: The error seems to be avoid by putting into comment the following lines of sntools_output.c

Line 430
#ifndef USE_HBOOK
  if ( TYPE_FLAG == IFILETYPE_HBOOK ) {
   // FMT = STRING_TABLEFILE_TYPE[TYPE_FLAG]; // "HBOOK"
   // sprintf(ENV,"CERN_DIR");                // required ENV for make
   //  TABLEFILE_notCompiled_ABORT(FILENAME, FMT, ENV);
  }

Line 446:
#ifndef USE_ROOT
  if ( TYPE_FLAG == IFILETYPE_ROOT ) {
   // FMT = STRING_TABLEFILE_TYPE[TYPE_FLAG];  // "ROOT"
   // sprintf(ENV,"ROOT_DIR");                 // required ENV for make
   // TABLEFILE_notCompiled_ABORT(FILENAME, FMT, ENV);
  }
#endif

**Comment by RickKessler** [comment] 2020-07-13 10:09
Sorry I missed this earlier, but I had not setup e-mail notifications because my collaborators have always been notifying me on slack. Anyway, hopefully the issue is fixed so please try again. If it works, please close this issue. What is strange is that CERN_DIR is not available at NERSC, yet I was able to compile the code at NERSC ?

**Closed** 2020-07-13 10:12 UTC
