### ISSUE TITLE
Tree = 'FITRES' does not exist error in WFIRST sims

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#191] opened 2020-07-25 19:58 UTC
Hi Rick, I'm trying to help our new WFIRST postdoc Phil make progress on the Hounsell et al. simulations.  A number of commands have been deprecated and one in particular is giving me a really opaque error.

In $SNANA_DEBUG/djones/wfirst, by running
```
split_and_fit.pl SIMFIT_WFIRST_Allz.NML
```

I get an error
```
Died at /project2/rkessler/PRODUCTS/SNANA/SNANA/util/sntable_dump.pl line 131.
```

when I check
```
SIMFIT_OUT/WFIRST_IMG-Allz_SHALLOW_PM/sntable_dump_FITOPT000_FITRES.log
```
I get this error:
```
 Begin sntable_dump.exe
 Table File : FITOPT000.ROOT
 Table ID   : FITRES
 Table VARNAME(0) : CCID
 Table VARNAME(1) : RA
 Table VARNAME(2) : DECL
 Table VARNAME(3) : TGAPMAX

 ******************************************************************
   OPEN_ROOTFILE: use  READ  mode:
   Opened FITOPT000.ROOT

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by get_tree
   Tree = 'FITRES' does not exist.
   Try another tree name.
```

Do you know what's going on?  Thanks!

**Comment by djones1040** [comment] 2020-07-25 19:59
assume this is related to the line:
```
APPEND_TABLE_TEXT: RA DECL TGAPMAX
```
but can't find any documentation as to what changed

**Comment by RickKessler** [comment] 2020-07-26 03:11
The above abort is a symptom, not the cause. The cause is that every snlc_fit job failed (see SPLIT_JOBS_LCFIT subdir). The failure is from a bug related to a subset of events having zero spectra (if NSPEC=0, was trying to read spectra ROW = -9). Bug fix propagated to Midway. If it works, please close this issue.

**Comment by djones1040** [comment] 2020-07-27 03:34
thanks Rick, the new error message is much more helpful.  Last thing is that it would help a lot to know what the allowed variables are, I'm not sure how to figure that out?  In any case, you can close this.

```
 FATAL ERROR ABORT called by SNTABLE_READPREP_VARDEF
   Could not find variable among VARLIST='DECL'
   Check variables in table = FITRES
```

**Comment by RickKessler** [comment] 2020-07-27 11:39
I'm going to close this snlc_fit issue. For SNTABLE_READPREP_VARDEF  issue above, please start separate GitHub issue and provide test job to reproduce the error.

**Closed by RickKessler** 2020-07-27 11:39 UTC
