### ISSUE TITLE
SNANA sim failed but output says SUCCESS

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#110] opened 2020-05-12 08:59 UTC
In `$SNANA_DEBUG/mvincenzi/DESSIMBIAS5YRIA_UVIR_G10` there are all the input files I used to run a SNe Ia simulation using `sim_SNmix`

SNANA says that the simulation finished without any problem and the output in FINISHED.DONE is SUCCESS. Also from the file TOTAL_SUMMARY.LOG everything seems to be ok.
However, if I untar the log files and I do:
` grep "ABORT" ./`
I find that 1 job aborted because of an error with one of the SN hosts

How to avoid the fact that aborted jobs are not picked-up?

**Comment by RickKessler** [comment] 2020-05-12 15:08
is this problem reproducible ? I suspect some kind of momentary disk access problem.

**Comment by RickKessler** [comment] 2020-05-13 00:09
I added an extra check that the log file exists before checking for abort, but don't know if this fixes issue. Since Sersic abort bug is fixed, going to close this issue as well. However, if this incorrect SUCCESS occurs again with a much shorter processing time, please submit another GitHub issue.

**Closed by RickKessler** 2020-05-13 00:09 UTC
